ctg:
  master:
    successors:
      - "slave1"
      - "slave2"
      - "slave3"
      - "slave4"
      - "slave5"
  slave1:
    successors:
      - "master"
  slave2:
    successors:
      - "master"
  slave3:
    successors:
      - "master"
  slave4:
    successors:
      - "master"
  slave5:
    successors:
      - "master"
