ctg:
  taskA:
    successors:
      - "taskC"
  taskB:
    successors:
      - "taskC"
  taskC:
    successors:
      - "taskD"
      - "taskE"
  taskD:
    successors:
      - "taskF"
  taskE:
    successors:
      - "taskF"
