ctg:
  master:
    successors:
      - "worker01"
      - "worker02"
      - "worker03"
      - "worker04"
      - "worker05"
      - "worker06"
      - "worker07"
      - "worker08"
      - "worker09"
      - "worker10"
      - "worker11"
      - "worker12"
      - "worker13"
      - "worker14"
      - "worker15"
      - "worker16"
      - "worker17"
      - "worker18"
      - "worker19"
      - "worker20"
      - "worker21"
      - "worker22"
      - "worker23"
      - "worker24"
      - "worker25"
      - "worker26"
      - "worker27"
      - "worker28"
      - "worker29"
      - "worker30"
      - "worker31"
