ctg:
  LAB1:
    successors:
      - "DLAB"
  LAB2:
    successors:
      - "DLAB"
  p1:
    successors:
      - "RMS"
      - "WRMS"
      - "GFC"
      - "XYZ1"
  p2:
    successors:
      - "RMS"
      - "WRMS"
      - "GFC"
      - "XYZ2"
  RGB1:
    successors:
      - "DRGB"
  RGB2:
    successors:
      - "DRGB"
  XYZ1:
    successors:
      - "LAB1"
      - "DXYZ"
      - "RGB1"
  XYZ2:
    successors:
      - "LAB2"
      - "DXYZ"
      - "RGB2"
