ctg:
  ACDC_0:
    successors:
      - "IQUANT_0"
      - "STRIPEM_0"
  ARM_0:
    successors:
      - "IDCT2_0"
  IDCT2_0:
    successors:
      - "UPSAMP_0"
  IQUANT_0:
    successors:
      - "IDCT2_0"
  ISCAN_0:
    successors:
      - "ACDC_0"
  PAD_0:
    successors:
      - "VOPME_0"
  RUN_0:
    successors:
      - "ISCAN_0"
  STRIPEN_0:
    successors:
      - "IQUANT_0"
  UPSAMP_0:
    successors:
      - "VOPREC_0"
  VLD_0:
    successors:
      - "RUN_0"
  VOPME_0:
    successors:
      - "PAD_0"
      - "VOPREC_0"
  VOPREC_0:
    successors:
      - "PAD_0"
