ctg:
  ADSP_0:
    successors:
      - "SDRAM_0"
  BAB_0:
    successors:
      - "SDRAM_0"
  IDCT_0:
    successors:
      - "SRAM2_0"
  MCPU_0:
    successors:
      - "SRAM1_0"
  RAST_0:
    successors:
      - "SDRAM_0"
  RISC_0:
    successors:
      - "SRAM2_0"
  SDRAM_0:
    successors:
      - "BAB_0"
      - "UPSAMP_0"
      - "ADSP_0"
      - "MCPU_0"
      - "RAST_0"
      - "AU_0"
      - "VU_0"
  SRAM1_0:
    successors:
      - "RAST_0"
  SRAM2_0:
    successors:
      - "RISC_0"
      - "BAB_0"
      - "IDCT_0"
      - "UPSAMP_0"
  UPSAMP_0:
    successors:
      - "SDRAM_0"
